{
    "name": "Inter Company and Intra Company Employee Transfer",
    'author': 'AppsComp Widgets Pvt Ltd',
    'category': 'Human Resources',
    "version": "17.0",
    'summary': "inter company and intra company employee transfer/employee transfer/company transfer/inter company transfer/intra company transfer/multi company employee transfer/employee company transfer/HR transfer/transfer approval/employee",
    'website': 'https://appscomp.com/',
    'images': ['static/description/gif.gif'],
    #'price': '42.09',
    'images': ['static/description/banner.png'],
    "depends": ['base', 'hr', 'apps_branch_master',
                'hr_holidays', 'hr_contract', 'hr_recruitment', 'account', 'om_hr_payroll',
                'om_hr_payroll_account'],
    'data': [
        'security/ir.model.access.csv',
        'views/employee_fields.xml',
        'views/company_transfer_view.xml',
        'views/grade_selection.xml',
        'data/grade.xml',
        'data/appointment_letter_data.xml',
    ],

    'qweb': [],
    'demo': [],
    'test': [],
    'css': [],
    'js': [],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
    'currency': 'EUR',
    'price': '59.54',
}
